<a href="https://colab.research.google.com/github/Khushbooyadav04/Weather_Forecast/blob/main/Weather_datasheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Weather_data.xlsx to Weather_data.xlsx

In [2]:
import io
df= pd.read_excel(io.BytesIO(uploaded["Weather_data.xlsx"]))

NameError: ignored

In [ ]:
df

                Date/Time  Temp_C  ...  Press_kPa               Weather
0     2012-01-01 00:00:00    -1.8  ...     101.24                   Fog
1     2012-01-01 01:00:00    -1.8  ...     101.24                   Fog
2     2012-01-01 02:00:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3     2012-01-01 03:00:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4     2012-01-01 04:00:00    -1.5  ...     101.23                   Fog
...                   ...     ...  ...        ...                   ...
8779     12/31/2012 19:00     0.1  ...     100.13                  Snow
8780     12/31/2012 20:00     0.2  ...     100.03                  Snow
8781     12/31/2012 21:00    -0.5  ...      99.95                  Snow
8782     12/31/2012 22:00    -0.2  ...      99.91                  Snow
8783     12/31/2012 23:00     0.0  ...      99.89                  Snow

[8784 rows x 8 columns]

In [ ]:
df.head()

             Date/Time  Temp_C  ...  Press_kPa               Weather
0  2012-01-01 00:00:00    -1.8  ...     101.24                   Fog
1  2012-01-01 01:00:00    -1.8  ...     101.24                   Fog
2  2012-01-01 02:00:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3  2012-01-01 03:00:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4  2012-01-01 04:00:00    -1.5  ...     101.23                   Fog

[5 rows x 8 columns]

In [ ]:
df.shape

(8784, 8)

In [ ]:
df.index

RangeIndex(start=0, stop=8784, step=1)

In [ ]:
df.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [ ]:
df.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [ ]:
df["Weather"].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [ ]:
df["Weather"].nunique()

50

In [ ]:
df.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

In [ ]:
df.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [ ]:
df["Weather"].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Moderate Snow                                 4
Rain,Haze                                     3
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Moderate Snow,Blowing Snow                    2
Drizzle,Snow                                  2
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Snow Pellets                                  1
Freezing Rain,Ice Pellets,Fog                 1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Drizzle,Ice Pellets,Fog                       1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Rain,Fog                        1
Name: Weather, dtype: int64

In [ ]:
df.head(2)

             Date/Time  Temp_C  ...  Press_kPa  Weather
0  2012-01-01 00:00:00    -1.8  ...     101.24      Fog
1  2012-01-01 01:00:00    -1.8  ...     101.24      Fog

[2 rows x 8 columns]

In [ ]:
df["Wind Speed_km/h"].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()
import io
df= pd.read_excel(io.BytesIO(uploaded["Weather_data.xlsx"])) 
df

Saving Weather_data.xlsx to Weather_data.xlsx

                Date/Time  Temp_C  ...  Press_kPa               Weather
0     2012-01-01 00:00:00    -1.8  ...     101.24                   Fog
1     2012-01-01 01:00:00    -1.8  ...     101.24                   Fog
2     2012-01-01 02:00:00    -1.8  ...     101.26  Freezing Drizzle,Fog
3     2012-01-01 03:00:00    -1.5  ...     101.27  Freezing Drizzle,Fog
4     2012-01-01 04:00:00    -1.5  ...     101.23                   Fog
...                   ...     ...  ...        ...                   ...
8779     12/31/2012 19:00     0.1  ...     100.13                  Snow
8780     12/31/2012 20:00     0.2  ...     100.03                  Snow
8781     12/31/2012 21:00    -0.5  ...      99.95                  Snow
8782     12/31/2012 22:00    -0.2  ...      99.91                  Snow
8783     12/31/2012 23:00     0.0  ...      99.89                  Snow

[8784 rows x 8 columns]

In [ ]:
df.head(2)

             Date/Time  Temp_C  ...  Press_kPa  Weather
0  2012-01-01 00:00:00    -1.8  ...     101.24      Fog
1  2012-01-01 01:00:00    -1.8  ...     101.24      Fog

[2 rows x 8 columns]

In [ ]:
df[df.Weather == "Clear"]

                Date/Time  Temp_C  ...  Press_kPa  Weather
67    2012-03-01 19:00:00   -16.9  ...     101.74    Clear
114   2012-05-01 18:00:00    -7.1  ...     100.71    Clear
115   2012-05-01 19:00:00    -9.2  ...     100.80    Clear
116   2012-05-01 20:00:00    -9.8  ...     100.83    Clear
117   2012-05-01 21:00:00    -9.0  ...     100.83    Clear
...                   ...     ...  ...        ...      ...
8646      12/26/2012 6:00   -13.4  ...     102.47    Clear
8698     12/28/2012 10:00    -6.1  ...     101.27    Clear
8713      12/29/2012 1:00   -11.9  ...     101.31    Clear
8714      12/29/2012 2:00   -11.8  ...     101.33    Clear
8756     12/30/2012 20:00   -13.8  ...     101.52    Clear

[1326 rows x 8 columns]

In [ ]:
df.head(2)

             Date/Time  Temp_C  ...  Press_kPa  Weather
0  2012-01-01 00:00:00    -1.8  ...     101.24      Fog
1  2012-01-01 01:00:00    -1.8  ...     101.24      Fog

[2 rows x 8 columns]

In [ ]:
df.groupby("Weather").get_group("Clear")

                Date/Time  Temp_C  ...  Press_kPa  Weather
67    2012-03-01 19:00:00   -16.9  ...     101.74    Clear
114   2012-05-01 18:00:00    -7.1  ...     100.71    Clear
115   2012-05-01 19:00:00    -9.2  ...     100.80    Clear
116   2012-05-01 20:00:00    -9.8  ...     100.83    Clear
117   2012-05-01 21:00:00    -9.0  ...     100.83    Clear
...                   ...     ...  ...        ...      ...
8646      12/26/2012 6:00   -13.4  ...     102.47    Clear
8698     12/28/2012 10:00    -6.1  ...     101.27    Clear
8713      12/29/2012 1:00   -11.9  ...     101.31    Clear
8714      12/29/2012 2:00   -11.8  ...     101.33    Clear
8756     12/30/2012 20:00   -13.8  ...     101.52    Clear

[1326 rows x 8 columns]

In [ ]:
df.head(2)

             Date/Time  Temp_C  ...  Press_kPa  Weather
0  2012-01-01 00:00:00    -1.8  ...     101.24      Fog
1  2012-01-01 01:00:00    -1.8  ...     101.24      Fog

[2 rows x 8 columns]

In [ ]:
df[df["Wind Speed_km/h"] == 4]

                Date/Time  Temp_C  ...  Press_kPa       Weather
0     2012-01-01 00:00:00    -1.8  ...     101.24           Fog
1     2012-01-01 01:00:00    -1.8  ...     101.24           Fog
96    2012-05-01 00:00:00    -8.8  ...     100.32          Snow
101   2012-05-01 05:00:00    -7.0  ...     100.19          Snow
146   2012-07-01 02:00:00    -8.1  ...     100.15        Cloudy
...                   ...     ...  ...        ...           ...
8768      12/31/2012 8:00    -8.6  ...     101.14  Snow Showers
8769      12/31/2012 9:00    -8.1  ...     101.09          Snow
8770     12/31/2012 10:00    -7.4  ...     101.05      Snow,Fog
8772     12/31/2012 12:00    -5.8  ...     100.78          Snow
8773     12/31/2012 13:00    -4.6  ...     100.63          Snow

[474 rows x 8 columns]

In [ ]:
df.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [ ]:
df.notnull().sum()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

In [ ]:
df.head(2)

             Date/Time  Temp_C  ...  Press_kPa  Weather
0  2012-01-01 00:00:00    -1.8  ...     101.24      Fog
1  2012-01-01 01:00:00    -1.8  ...     101.24      Fog

[2 rows x 8 columns]

In [ ]:
df.rename(columns ={"Weather" :"Weather condition"}, inplace=True)

In [ ]:
df.head(2)

             Date/Time  Temp_C  ...  Press_kPa  Weather condition
0  2012-01-01 00:00:00    -1.8  ...     101.24                Fog
1  2012-01-01 01:00:00    -1.8  ...     101.24                Fog

[2 rows x 8 columns]

In [ ]:
df.head(2)

             Date/Time  Temp_C  ...  Press_kPa  Weather condition
0  2012-01-01 00:00:00    -1.8  ...     101.24                Fog
1  2012-01-01 01:00:00    -1.8  ...     101.24                Fog

[2 rows x 8 columns]

In [ ]:
df.Visibility_km.mean()

27.66444672131151

In [ ]:
df.Press_kPa.std()

0.8440047459486474

In [ ]:
df['Rel Hum_%'].var()

286.2485501984998

In [ ]:
df["Weather condition"].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Rain,Snow,Ice Pellets                         4
Moderate Snow                                 4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Thunderstorms                                 2
Rain Showers,Snow Showers                     2
Drizzle,Snow                                  2
Freezing Rain,Haze                            2
Moderate Snow,Blowing Snow                    2
Rain,Snow Grains                              1
Rain,Ice Pellets                              1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Thunderstorms,Rain,Fog                        1
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Heavy Rain Showers              1
Rain,Snow,Fog                                 1
Drizzle,Ice Pellets,Fog                       1
Freezing Rain,Snow Grains                     1
Snow Pellets                                  1
Name: Weather condition, dtype: int64

In [ ]:
df[df["Weather condition"]=="Snow"]

                Date/Time  Temp_C  ...  Press_kPa  Weather condition
55    2012-03-01 07:00:00   -14.0  ...     100.95               Snow
84    2012-04-01 12:00:00   -13.7  ...     101.25               Snow
86    2012-04-01 14:00:00   -11.3  ...     100.97               Snow
87    2012-04-01 15:00:00   -10.2  ...     100.89               Snow
88    2012-04-01 16:00:00    -9.4  ...     100.79               Snow
...                   ...     ...  ...        ...                ...
8779     12/31/2012 19:00     0.1  ...     100.13               Snow
8780     12/31/2012 20:00     0.2  ...     100.03               Snow
8781     12/31/2012 21:00    -0.5  ...      99.95               Snow
8782     12/31/2012 22:00    -0.2  ...      99.91               Snow
8783     12/31/2012 23:00     0.0  ...      99.89               Snow

[390 rows x 8 columns]

In [ ]:
df[df["Weather condition"].str.contains('Snow')].tail(50)

             Date/Time  Temp_C  ...  Press_kPa      Weather condition
8680  12/27/2012 16:00    -4.5  ...     100.44      Snow,Blowing Snow
8681  12/27/2012 17:00    -4.2  ...     100.47      Snow,Blowing Snow
8682  12/27/2012 18:00    -4.0  ...     100.49      Snow,Blowing Snow
8683  12/27/2012 19:00    -3.9  ...     100.52      Snow,Blowing Snow
8684  12/27/2012 20:00    -3.7  ...     100.58                   Snow
8685  12/27/2012 21:00    -3.7  ...     100.62  Freezing Drizzle,Snow
8686  12/27/2012 22:00    -3.8  ...     100.65  Freezing Drizzle,Snow
8687  12/27/2012 23:00    -4.0  ...     100.70                   Snow
8688   12/28/2012 0:00    -4.2  ...     100.78  Freezing Drizzle,Snow
8689   12/28/2012 1:00    -4.4  ...     100.83  Freezing Drizzle,Snow
8690   12/28/2012 2:00    -4.3  ...     100.93  Freezing Drizzle,Snow
8691   12/28/2012 3:00    -4.6  ...     101.01                   Snow
8692   12/28/2012 4:00    -4.9  ...     101.00                   Snow
8723  12/29/2012 11:00   -10.9  ...     101.09       Snow Showers,Fog
8724  12/29/2012 12:00   -10.5  ...     100.93       Snow Showers,Fog
8725  12/29/2012 13:00   -10.0  ...     100.63       Snow Showers,Fog
8726  12/29/2012 14:00    -9.3  ...     100.60               Snow,Fog
8727  12/29/2012 15:00    -8.8  ...     100.55               Snow,Fog
8728  12/29/2012 16:00    -8.5  ...     100.49               Snow,Fog
8729  12/29/2012 17:00    -9.0  ...     100.46               Snow,Fog
8730  12/29/2012 18:00    -9.3  ...     100.38               Snow,Fog
8731  12/29/2012 19:00    -9.5  ...     100.33               Snow,Fog
8732  12/29/2012 20:00    -9.7  ...     100.25               Snow,Fog
8733  12/29/2012 21:00    -9.8  ...     100.24               Snow,Fog
8734  12/29/2012 22:00   -10.1  ...     100.20               Snow,Fog
8735  12/29/2012 23:00   -10.0  ...     100.19               Snow,Fog
8736   12/30/2012 0:00    -9.6  ...     100.23               Snow,Fog
8737   12/30/2012 1:00    -9.4  ...     100.22               Snow,Fog
8738   12/30/2012 2:00    -9.3  ...     100.28               Snow,Fog
8739   12/30/2012 3:00    -9.1  ...     100.30               Snow,Fog
8740   12/30/2012 4:00    -9.3  ...     100.28               Snow,Fog
8741   12/30/2012 5:00    -9.1  ...     100.32               Snow,Fog
8742   12/30/2012 6:00    -9.3  ...     100.39               Snow,Fog
8767   12/31/2012 7:00    -9.3  ...     101.19           Snow Showers
8768   12/31/2012 8:00    -8.6  ...     101.14           Snow Showers
8769   12/31/2012 9:00    -8.1  ...     101.09                   Snow
8770  12/31/2012 10:00    -7.4  ...     101.05               Snow,Fog
8771  12/31/2012 11:00    -6.7  ...     100.93                   Snow
8772  12/31/2012 12:00    -5.8  ...     100.78                   Snow
8773  12/31/2012 13:00    -4.6  ...     100.63                   Snow
8774  12/31/2012 14:00    -3.4  ...     100.57                   Snow
8775  12/31/2012 15:00    -2.3  ...     100.47                   Snow
8776  12/31/2012 16:00    -1.4  ...     100.40                   Snow
8777  12/31/2012 17:00    -1.1  ...     100.30                   Snow
8778  12/31/2012 18:00    -1.3  ...     100.19                   Snow
8779  12/31/2012 19:00     0.1  ...     100.13                   Snow
8780  12/31/2012 20:00     0.2  ...     100.03                   Snow
8781  12/31/2012 21:00    -0.5  ...      99.95                   Snow
8782  12/31/2012 22:00    -0.2  ...      99.91                   Snow
8783  12/31/2012 23:00     0.0  ...      99.89                   Snow

[50 rows x 8 columns]

In [ ]:
df.head(2)

             Date/Time  Temp_C  ...  Press_kPa  Weather condition
0  2012-01-01 00:00:00    -1.8  ...     101.24                Fog
1  2012-01-01 01:00:00    -1.8  ...     101.24                Fog

[2 rows x 8 columns]

In [ ]:
df[(df["Wind Speed_km/h"] > 24) & (df["Visibility_km"] == 25)]

                Date/Time  Temp_C  ...  Press_kPa  Weather condition
23    2012-01-01 23:00:00     5.3  ...      99.31             Cloudy
24    2012-02-01 00:00:00     5.2  ...      99.26       Rain Showers
25    2012-02-01 01:00:00     4.6  ...      99.26             Cloudy
26    2012-02-01 02:00:00     3.9  ...      99.26      Mostly Cloudy
27    2012-02-01 03:00:00     3.7  ...      99.30      Mostly Cloudy
...                   ...     ...  ...        ...                ...
8705     12/28/2012 17:00    -8.6  ...     101.34       Mainly Clear
8753     12/30/2012 17:00   -12.1  ...     101.26       Mainly Clear
8755     12/30/2012 19:00   -13.4  ...     101.47       Mainly Clear
8759     12/30/2012 23:00   -12.1  ...     101.52      Mostly Cloudy
8760      12/31/2012 0:00   -11.1  ...     101.51             Cloudy

[308 rows x 8 columns]

In [ ]:
df.head(2)

             Date/Time  Temp_C  ...  Press_kPa  Weather condition
0  2012-01-01 00:00:00    -1.8  ...     101.24                Fog
1  2012-01-01 01:00:00    -1.8  ...     101.24                Fog

[2 rows x 8 columns]

In [ ]:
df.groupby("Weather condition").mean()

                                            Temp_C  ...   Press_kPa
Weather condition                                   ...
Clear                                     6.825716  ...  101.587443
Cloudy                                    7.970544  ...  100.911441
Drizzle                                   7.353659  ...  100.435366
Drizzle,Fog                               8.067500  ...  100.786625
Drizzle,Ice Pellets,Fog                   0.400000  ...  100.790000
Drizzle,Snow                              1.050000  ...  100.890000
Drizzle,Snow,Fog                          0.693333  ...   99.281333
Fog                                       4.303333  ...  101.184067
Freezing Drizzle                         -5.657143  ...  100.202857
Freezing Drizzle,Fog                     -2.533333  ...  100.441667
Freezing Drizzle,Haze                    -5.433333  ...  100.316667
Freezing Drizzle,Snow                    -5.109091  ...  100.520909
Freezing Fog                             -7.575000  ...  102.320000
Freezing Rain                            -3.885714  ...   99.647143
Freezing Rain,Fog                        -2.225000  ...   99.945000
Freezing Rain,Haze                       -4.900000  ...  100.375000
Freezing Rain,Ice Pellets,Fog            -2.600000  ...  100.950000
Freezing Rain,Snow Grains                -5.000000  ...   98.560000
Haze                                     -0.200000  ...  101.482500
Mainly Clear                             12.558927  ...  101.248832
Moderate Rain,Fog                         1.700000  ...   99.980000
Moderate Snow                            -5.525000  ...  100.275000
Moderate Snow,Blowing Snow               -5.450000  ...  100.570000
Mostly Cloudy                            10.574287  ...  101.025288
Rain                                      9.786275  ...  100.233333
Rain Showers                             13.722340  ...  100.404043
Rain Showers,Fog                         12.800000  ...   99.830000
Rain Showers,Snow Showers                 2.150000  ...  101.100000
Rain,Fog                                  8.273276  ...  100.500862
Rain,Haze                                 4.633333  ...  100.540000
Rain,Ice Pellets                          0.600000  ...  100.120000
Rain,Snow                                 1.055556  ...   99.951111
Rain,Snow Grains                          1.900000  ...  100.600000
Rain,Snow,Fog                             0.800000  ...  100.730000
Rain,Snow,Ice Pellets                     1.100000  ...  100.105000
Snow                                     -4.524103  ...  100.536103
Snow Pellets                              0.700000  ...   99.700000
Snow Showers                             -3.506667  ...  100.963500
Snow Showers,Fog                        -10.675000  ...  101.292500
Snow,Blowing Snow                        -5.410526  ...   99.704737
Snow,Fog                                 -5.075676  ...  100.688649
Snow,Haze                                -4.020000  ...  100.782000
Snow,Ice Pellets                         -1.883333  ...  100.548333
Thunderstorms                            24.150000  ...  100.230000
Thunderstorms,Heavy Rain Showers         10.900000  ...  100.260000
Thunderstorms,Moderate Rain Showers,Fog  19.600000  ...  100.010000
Thunderstorms,Rain                       20.433333  ...  100.420000
Thunderstorms,Rain Showers               20.037500  ...  100.233750
Thunderstorms,Rain Showers,Fog           21.600000  ...  100.063333
Thunderstorms,Rain,Fog                   20.600000  ...  100.080000

[50 rows x 6 columns]

In [ ]:
df.head(2)

             Date/Time  Temp_C  ...  Press_kPa  Weather condition
0  2012-01-01 00:00:00    -1.8  ...     101.24                Fog
1  2012-01-01 01:00:00    -1.8  ...     101.24                Fog

[2 rows x 8 columns]

In [ ]:
df.groupby("Weather condition").min()

                                         Temp_C  ...  Press_kPa
Weather condition                                ...
Clear                                     -23.3  ...      99.52
Cloudy                                    -21.4  ...      98.39
Drizzle                                     1.1  ...      97.84
Drizzle,Fog                                 0.0  ...      98.65
Drizzle,Ice Pellets,Fog                     0.4  ...     100.79
Drizzle,Snow                                0.9  ...     100.63
Drizzle,Snow,Fog                            0.3  ...      97.79
Fog                                       -16.0  ...      98.31
Freezing Drizzle                           -9.0  ...      98.44
Freezing Drizzle,Fog                       -6.4  ...      98.74
Freezing Drizzle,Haze                      -5.8  ...     100.28
Freezing Drizzle,Snow                      -8.3  ...      99.19
Freezing Fog                              -19.0  ...     101.97
Freezing Rain                              -6.5  ...      98.22
Freezing Rain,Fog                          -6.1  ...      98.32
Freezing Rain,Haze                         -4.9  ...     100.34
Freezing Rain,Ice Pellets,Fog              -2.6  ...     100.95
Freezing Rain,Snow Grains                  -5.0  ...      98.56
Haze                                      -11.5  ...     100.35
Mainly Clear                              -22.8  ...      98.67
Moderate Rain,Fog                           1.7  ...      99.98
Moderate Snow                              -6.3  ...      99.88
Moderate Snow,Blowing Snow                 -5.5  ...     100.50
Mostly Cloudy                             -23.2  ...      98.36
Rain                                        0.3  ...      97.52
Rain Showers                                1.6  ...      98.51
Rain Showers,Fog                           12.8  ...      99.83
Rain Showers,Snow Showers                   2.1  ...     101.09
Rain,Fog                                    0.0  ...      98.61
Rain,Haze                                   4.0  ...     100.50
Rain,Ice Pellets                            0.6  ...     100.12
Rain,Snow                                   0.6  ...      98.18
Rain,Snow Grains                            1.9  ...     100.60
Rain,Snow,Fog                               0.8  ...     100.73
Rain,Snow,Ice Pellets                       0.9  ...      99.85
Snow                                      -16.7  ...      97.75
Snow Pellets                                0.7  ...      99.70
Snow Showers                              -13.3  ...      99.49
Snow Showers,Fog                          -11.3  ...     100.63
Snow,Blowing Snow                         -12.0  ...      98.11
Snow,Fog                                  -10.1  ...      99.38
Snow,Haze                                  -4.3  ...     100.61
Snow,Ice Pellets                           -4.3  ...      99.40
Thunderstorms                              21.6  ...      99.84
Thunderstorms,Heavy Rain Showers           10.9  ...     100.26
Thunderstorms,Moderate Rain Showers,Fog    19.6  ...     100.01
Thunderstorms,Rain                         19.4  ...     100.19
Thunderstorms,Rain Showers                 11.0  ...      99.65
Thunderstorms,Rain Showers,Fog             19.5  ...      99.71
Thunderstorms,Rain,Fog                     20.6  ...     100.08

[50 rows x 6 columns]

In [ ]:
df.groupby("Weather condition").max()

                                         Temp_C  ...  Press_kPa
Weather condition                                ...
Clear                                      32.8  ...     103.63
Cloudy                                     30.5  ...     103.65
Drizzle                                    18.8  ...     101.56
Drizzle,Fog                                19.9  ...     102.07
Drizzle,Ice Pellets,Fog                     0.4  ...     100.79
Drizzle,Snow                                1.2  ...     101.15
Drizzle,Snow,Fog                            1.1  ...     100.15
Fog                                        20.8  ...     103.04
Freezing Drizzle                           -2.3  ...     101.02
Freezing Drizzle,Fog                       -0.3  ...     101.27
Freezing Drizzle,Haze                      -5.0  ...     100.36
Freezing Drizzle,Snow                      -3.3  ...     101.18
Freezing Fog                               -0.1  ...     102.85
Freezing Rain                               0.3  ...     101.00
Freezing Rain,Fog                           0.1  ...     101.01
Freezing Rain,Haze                         -4.9  ...     100.41
Freezing Rain,Ice Pellets,Fog              -2.6  ...     100.95
Freezing Rain,Snow Grains                  -5.0  ...      98.56
Haze                                       14.1  ...     102.97
Mainly Clear                               33.0  ...     103.59
Moderate Rain,Fog                           1.7  ...      99.98
Moderate Snow                              -4.9  ...     100.67
Moderate Snow,Blowing Snow                 -5.4  ...     100.64
Mostly Cloudy                              32.4  ...     103.65
Rain                                       22.8  ...     102.26
Rain Showers                               26.4  ...     102.31
Rain Showers,Fog                           12.8  ...      99.83
Rain Showers,Snow Showers                   2.2  ...     101.11
Rain,Fog                                   21.7  ...     101.77
Rain,Haze                                   5.5  ...     100.61
Rain,Ice Pellets                            0.6  ...     100.12
Rain,Snow                                   1.7  ...     101.07
Rain,Snow Grains                            1.9  ...     100.60
Rain,Snow,Fog                               0.8  ...     100.73
Rain,Snow,Ice Pellets                       1.3  ...     100.47
Snow                                        3.7  ...     102.73
Snow Pellets                                0.7  ...      99.70
Snow Showers                                2.9  ...     102.50
Snow Showers,Fog                          -10.0  ...     102.52
Snow,Blowing Snow                          -1.4  ...     100.62
Snow,Fog                                    1.1  ...     102.07
Snow,Haze                                  -3.6  ...     100.99
Snow,Ice Pellets                            0.8  ...     100.96
Thunderstorms                              26.7  ...     100.62
Thunderstorms,Heavy Rain Showers           10.9  ...     100.26
Thunderstorms,Moderate Rain Showers,Fog    19.6  ...     100.01
Thunderstorms,Rain                         21.3  ...     100.83
Thunderstorms,Rain Showers                 25.5  ...     101.06
Thunderstorms,Rain Showers,Fog             22.9  ...     100.64
Thunderstorms,Rain,Fog                     20.6  ...     100.08

[50 rows x 6 columns]